// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/entry/list": {
            "get": {
                "description": "分页列出条目，可按渠道、已读/收藏/归档状态过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "列出条目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（从1开始）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "按渠道过滤",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按已读状态过滤",
                        "name": "read",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按收藏状态过滤",
                        "name": "favorite",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按归档状态过滤",
                        "name": "archive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryListResponse"
                        }
                    }
                }
            }
        },
        "/entry/read-later": {
            "get": {
                "description": "分页列出标记为「稍后再阅」的条目，按加入时间倒序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "列出稍后再阅条目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（从1开始）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryListResponse"
                        }
                    }
                }
            }
        },
        "/entry/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "获取单个条目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "条目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/entry/{id}/archive": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "设置/取消归档",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "条目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/entry/{id}/favorite": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "设置/取消收藏",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "条目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/entry/{id}/read": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "设置/取消已读",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "条目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/entry/{id}/read-later": {
            "put": {
                "description": "标记或取消标记条目的「稍后再阅」状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "设置/取消稍后再阅",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "条目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/os/info": {
            "get": {
                "description": "获取主机名、操作系统、CPU 与内存等基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统信息"
                ],
                "summary": "获取操作系统信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.OsInfo"
                        }
                    }
                }
            }
        },
        "/os/state": {
            "get": {
                "description": "获取系统的运行时长、空闲内存与 CPU 使用率",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统信息"
                ],
                "summary": "获取操作系统状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.OsState"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "遍历所有启用的渠道拉取新内容并写库（三层去重）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refresh"
                ],
                "summary": "手动触发一轮采集",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.RefreshResult"
                        }
                    }
                }
            }
        },
        "/refresh/stream": {
            "get": {
                "description": "以 Server-Sent Events 实时推送采集进度（渠道开始/完成/失败），供前端显示进度与新内容高亮",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "refresh"
                ],
                "summary": "订阅采集进度（SSE）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ProgressEvent"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "检索条目标题/摘要/正文/作者；中文按 bigram 分词，多词按 AND 匹配",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "全文检索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码（从1开始）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "按渠道过滤",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按已读状态过滤",
                        "name": "read",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按收藏状态过滤",
                        "name": "favorite",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按归档状态过滤",
                        "name": "archive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.EntryListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/source": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "列出渠道实例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "校验配置后入库（走适配器 Validate，失败不入库）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "新增渠道实例",
                "parameters": [
                    {
                        "description": "渠道参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/source/probe": {
            "post": {
                "description": "在保存前探测渠道元信息（如 feed 标题），供「自动获取显示名」使用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "探测渠道元信息",
                "parameters": [
                    {
                        "description": "渠道类型与配置",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SourceProbeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/source.ProbeInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/source/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "获取单个渠道实例",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "渠道实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "更新渠道实例",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "渠道实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "渠道参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "删除渠道实例（软删除）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "渠道实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/source/{id}/logs": {
            "get": {
                "description": "按时间倒序返回指定渠道最近的采集日志，用于排障",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "列出渠道采集日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "渠道实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回条数上限（默认 50，最大 200）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.FetchLogListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sys/info": {
            "get": {
                "description": "获取服务的启动时间、构建时间与版本信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统信息"
                ],
                "summary": "获取系统信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SysInfo"
                        }
                    }
                }
            }
        },
        "/sys/state": {
            "get": {
                "description": "获取服务的运行时长、协程数、堆内存与 GC 次数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统状态"
                ],
                "summary": "获取系统状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SysState"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ProgressEvent": {
            "type": "object",
            "properties": {
                "elapsed_ms": {
                    "description": "耗时（毫秒）",
                    "type": "integer"
                },
                "error": {
                    "description": "错误信息",
                    "type": "string"
                },
                "inserted": {
                    "description": "新增条目数",
                    "type": "integer"
                },
                "inserted_ids": {
                    "description": "新增条目ID（供前端高亮）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "skipped": {
                    "description": "去重跳过数",
                    "type": "integer"
                },
                "source_id": {
                    "description": "渠道ID（source_* 事件）",
                    "type": "integer"
                },
                "source_name": {
                    "description": "渠道显示名",
                    "type": "string"
                },
                "type": {
                    "description": "事件类型（见 Event* 常量）",
                    "type": "string"
                }
            }
        },
        "app.RefreshResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "错误信息",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inserted": {
                    "description": "新入库条目数",
                    "type": "integer"
                },
                "inserted_ids": {
                    "description": "本轮新增条目的 ID（供前端高亮新内容）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "skipped": {
                    "description": "去重跳过的条目数",
                    "type": "integer"
                },
                "sources": {
                    "description": "处理的渠道数",
                    "type": "integer"
                }
            }
        },
        "server.EntryDTO": {
            "type": "object",
            "properties": {
                "archive": {
                    "description": "是否已归档",
                    "type": "boolean"
                },
                "author": {
                    "description": "作者",
                    "type": "string"
                },
                "content": {
                    "description": "正文",
                    "type": "string"
                },
                "content_type": {
                    "description": "内容类型",
                    "type": "string"
                },
                "extra": {
                    "description": "渠道特有字段",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "favorite": {
                    "description": "是否已收藏",
                    "type": "boolean"
                },
                "fetched_at": {
                    "description": "抓取时间（RFC3339）",
                    "type": "string"
                },
                "guid": {
                    "description": "渠道自带稳定ID",
                    "type": "string"
                },
                "id": {
                    "description": "条目ID",
                    "type": "integer"
                },
                "published_at": {
                    "description": "发布时间（RFC3339）",
                    "type": "string"
                },
                "read": {
                    "description": "是否已读",
                    "type": "boolean"
                },
                "read_later": {
                    "description": "是否已加入「稍后再阅」",
                    "type": "boolean"
                },
                "source_id": {
                    "description": "归属渠道实例ID",
                    "type": "integer"
                },
                "summary": {
                    "description": "摘要",
                    "type": "string"
                },
                "tags": {
                    "description": "标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "url": {
                    "description": "规范化后的链接",
                    "type": "string"
                }
            }
        },
        "server.EntryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "条目列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.EntryDTO"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "server.FetchLogDTO": {
            "type": "object",
            "properties": {
                "elapsed_ms": {
                    "description": "耗时（毫秒）",
                    "type": "integer"
                },
                "error": {
                    "description": "错误信息（成功为空）",
                    "type": "string"
                },
                "id": {
                    "description": "日志ID",
                    "type": "integer"
                },
                "inserted": {
                    "description": "新增条目数",
                    "type": "integer"
                },
                "skipped": {
                    "description": "去重跳过数",
                    "type": "integer"
                },
                "source_id": {
                    "description": "归属渠道实例ID",
                    "type": "integer"
                },
                "started_at": {
                    "description": "采集开始时间（RFC3339）",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        },
        "server.FetchLogListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "日志列表（按时间倒序）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.FetchLogDTO"
                    }
                },
                "total": {
                    "description": "返回条数",
                    "type": "integer"
                }
            }
        },
        "server.OsInfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "description": "系统架构",
                    "type": "string"
                },
                "cpu_count": {
                    "description": "CPU 核心数",
                    "type": "integer"
                },
                "cpu_model": {
                    "description": "CPU 型号",
                    "type": "string"
                },
                "hostname": {
                    "description": "主机名",
                    "type": "string"
                },
                "os_name": {
                    "description": "操作系统名称",
                    "type": "string"
                },
                "platform": {
                    "description": "系统平台",
                    "type": "string"
                },
                "start_time": {
                    "description": "系统启动时间（RFC3339）",
                    "type": "string"
                },
                "total_mem_mb": {
                    "description": "总内存（MB）",
                    "type": "integer"
                }
            }
        },
        "server.OsState": {
            "type": "object",
            "properties": {
                "cpu_freq": {
                    "description": "CPU 频率",
                    "type": "string"
                },
                "cpu_percent": {
                    "description": "CPU 使用率（%）",
                    "type": "integer"
                },
                "free_mem_mb": {
                    "description": "空闲内存（MB）",
                    "type": "integer"
                },
                "uptime": {
                    "description": "运行时长",
                    "type": "string"
                }
            }
        },
        "server.SourceDTO": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "渠道配置 JSON 对象",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "fail_count": {
                    "description": "连续失败次数",
                    "type": "integer"
                },
                "fetch_count": {
                    "description": "累计采集次数",
                    "type": "integer"
                },
                "id": {
                    "description": "渠道实例ID",
                    "type": "integer"
                },
                "interval": {
                    "description": "刷新间隔（秒）",
                    "type": "integer"
                },
                "last_elapsed_ms": {
                    "description": "最近一次耗时（毫秒）",
                    "type": "integer"
                },
                "last_entry_at": {
                    "description": "最新条目的发布时间",
                    "type": "string"
                },
                "last_error": {
                    "description": "最近一次错误",
                    "type": "string"
                },
                "last_fetch_at": {
                    "description": "最近一次采集时间（RFC3339）",
                    "type": "string"
                },
                "last_success_at": {
                    "description": "最后成功时间（RFC3339）",
                    "type": "string"
                },
                "name": {
                    "description": "显示名",
                    "type": "string"
                },
                "success_count": {
                    "description": "累计成功次数",
                    "type": "integer"
                },
                "success_rate": {
                    "description": "成功率（0~1）",
                    "type": "number"
                },
                "type": {
                    "description": "渠道类型标识",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "server.SourceListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "渠道列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.SourceDTO"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "server.SourceProbeRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "渠道配置 JSON 对象",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "type": {
                    "description": "渠道类型标识",
                    "type": "string"
                }
            }
        },
        "server.SourceRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "渠道配置 JSON 对象",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "enabled": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "interval": {
                    "description": "刷新间隔（秒）",
                    "type": "integer"
                },
                "name": {
                    "description": "显示名",
                    "type": "string"
                },
                "type": {
                    "description": "渠道类型标识",
                    "type": "string"
                }
            }
        },
        "server.SysInfo": {
            "type": "object",
            "properties": {
                "build_time": {
                    "description": "构建时间",
                    "type": "string"
                },
                "build_version": {
                    "description": "构建版本",
                    "type": "string"
                },
                "go_version": {
                    "description": "Go 版本",
                    "type": "string"
                },
                "start_time": {
                    "description": "服务启动时间（RFC3339）",
                    "type": "string"
                }
            }
        },
        "server.SysState": {
            "type": "object",
            "properties": {
                "gc_total_count": {
                    "description": "垃圾回收总次数",
                    "type": "integer"
                },
                "heap_used_mb": {
                    "description": "堆内存使用量（MB）",
                    "type": "integer"
                },
                "num_goroutine": {
                    "description": "当前协程数",
                    "type": "integer"
                },
                "uptime": {
                    "description": "运行时长",
                    "type": "string"
                }
            }
        },
        "source.ProbeInfo": {
            "type": "object",
            "properties": {
                "title": {
                    "description": "渠道标题（如 feed 的 \u003ctitle\u003e），可能为空",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "NewsGlean API",
	Description:      "拾取、清洗、归档你关心的内容。把 RSS、网页、聊天机器人里的信息统一成同一个阅读流。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
